### PR TITLE
add suport to django-health-check

### PR DESCRIPTION
**Pull request by chaws**
This package allows simple system checks to be made in a running SQUAD instance. The full configuration should take place in an external set up file.

This is how it's going to look:

Screenshot from 2021-04-23 00-41-21

For more information, please read:
https://django-health-check.readthedocs.io/en/stable/readme.html#

### CODE REVIEW

**Comment by jscook2345** [comment]
LGTM

**Comment by jscook2345** [comment]
Still LGTM!

**Comment by chaws** [comment]
@jscook2345 thanks for the reminder :) , I've added a menu next to "Administrator" submenu and also restricted this url access to logged users with staff permissions. Also json is supported by passing an auth token in the header request. I'm planning on adding an external monitoring tool for that, like grafana

**Comment by chaws** [comment]
Tests are all green. I'm merging this and test it in staging before releasing it to prod

**Pull request merged**
