### PR TITLE
(WIP) add test details page.

### PR DESCRIPTION
**Pull request by amrohassaan**
squad: frontend: add testcase metadata, history and logs to tests page
with downloadables about this testcase. And removed testrun page.
Changed all links in builds view to route to tests directly.

### CODE REVIEW

**Comment by amrohassaan** [comment]
Details on tests
Test Details

Test Details page
Old Testrun

No testruns listing in build view.
Removed Testruns

@mwasilew , @chaws talk about this Monday.

**Comment by mwasilew** [comment]
@amrohassaan it's a good attempt. Some immediate issues I found when using it:
 - test details page should be default when accessing the test from suite page
 - only display 'important' metadata for project (I'm not sure about that, but let's try it)
 - test result isn't displayed anywhere in the test details page
 - breadcrumb for test is missing in the top header

I'll look at the code once it passes unit tests.

**Comment by amrohassaan** [comment]
@chaws @mwasilew please review.

**Comment by amrohassaan** [comment]
add_testdetails

add_testdetails2
testrun.id in url

**Comment by mwasilew** [comment]
I guess we can't agree on what the details page should look like. This is how I would like to have it:
squad_test_details

Here is the diff on top of the current patch:
```
diff --git a/squad/frontend/templates/squad/test_run_suite_test_details.jinja2 b/squad/frontend/templates/squad/test_run_suite_test_details.jinja2
index 6a6cae1..225a82d 100644
--- a/squad/frontend/templates/squad/test_run_suite_test_details.jinja2
+++ b/squad/frontend/templates/squad/test_run_suite_test_details.jinja2
@@ -7,12 +7,53 @@
     » <a class="h2 text-primary" href="{{testrun_suite_tests_url(project.group, project, build, status)}}">{{suite}}</a>
     » <a class="h2 text-primary" href="#">{{test.name}}</a>
     <br>
-    {% include "squad/_env_suite_data.jinja2" %}
-    <a name="tests"></a>
 </h2>
 
 {% include "squad/tests-details-nav.jinja2" %}
 
+<h3>Test details:<h3>
+      <i class='fa fa-microchip'></i>
+      <span class='p-3 mb-2 text-dark'>
+      {{ (_('Test environment: <strong>%s</strong>') % test_run.environment) | safe }}
+      </span>
+      {% if test_run.environment.description %}
+      <span onclick="$('#environment-description').toggle(); return false" class='btn btn-xs'><span class='fa fa-info'></span></span>
+      {% endif %}
+      {% if test_run.environment.description %}
+      <div class='alert' id='environment-description' style='display: none'>
+        {{test_run.environment.description|markdown}}
+      </div>
+      {% endif %}
+      <br>
+      <i class='fa fa-list'></i>
+      <span class='p-3 mb-2 text-dark'>{{ (_('Suite: <strong>%s</strong>') % suite) | safe }}
+      {% if status.suite_version %}
+      {{status.suite_version.version}}
+      {% endif %}
+      </span>
+      <br>
+      {% if test %}
+      <i class='fa fa-crosshairs'></i>
+      <span class='p-3 mb-2 text-dark'>{{ (_('Test: <strong>%s</strong>') % test) | safe }}
+      </span>
+      <br>
+      <span class='p-3 mb-2 text-dark'>{{ (_('Test result: <strong>%s</strong>') % test.status) | safe }}
+      </span>
+      {% endif %}
+      {% if suite.metadata.description %}
+      <br>
+      <span onclick="$('#tests-{{suite.slug}}-description').toggle(); return false" class='btn btn-xs btn-info'><span class='fa fa-info'></span></span>
+      {% endif %}
+      {% if suite.metadata.description %}
+      <br>
+      <div class='alert alert-info' id='tests-{{suite.slug}}-description' style='display: none'>
+        {{suite.metadata.description|markdown}}
+      </div>
+      {% endif %}
+      <br>
+      <span class='p-3 mb-2 text-dark'>{{ (_('Build:')) }}<strong><a href="{{ build_url(build) }}" class='p-3 mb-2 text-dark'>{{ test.test_run.build.version | safe }}</a></strong>
+      </span>
+
 {% include "squad/test_run.jinja2" %}
 
 {% endblock %}
diff --git a/squad/frontend/templates/squad/tests-details-nav.jinja2 b/squad/frontend/templates/squad/tests-details-nav.jinja2
index a22f434..6968c5f 100644
--- a/squad/frontend/templates/squad/tests-details-nav.jinja2
+++ b/squad/frontend/templates/squad/tests-details-nav.jinja2
@@ -2,6 +2,11 @@
     {% with url_name=request.resolver_match.url_name %}
 
     <li role="presentation" {% if url_name == 'testrun_suite_test_details' %}class="active"{% endif %}>
+       <a href="{{testrun_suite_test_details_url(project.group, project, build, status, test)}}">
+           {{ _('Details') }}
+       </a>
+    </li>
+    <li role="presentation" {% if url_name == 'testrun_suite_test_metadata' %}class="active"{% endif %}>
        <a href="{{testrun_suite_test_details_url(project.group, project, build, status, test)}}">
            {{ _('Metadata') }}
        </a>
```
Test result color coding can be added. Maybe test result and build should be accompanied with icons. But in general this is what I would like to see. Also it would be nice to check how it looks like with all metadata filled in and expanded. Additional features should be:
 - test description (if exists)
 - test steps to reproduce (if they exist)
 - known issues (if registered for this test)

**Comment by amrohassaan** [comment]
@mwasilew ok, didn't capture you wanted the details to really stand out individually but i get your point ..makes sense. 
will try to add the extra data locally to see how it looks like (eg. steps to reproduce).

**Comment by amrohassaan** [comment]
@mwasilew created some dummy test.description and env.description and test.instructions. Not known issues which i wanna ask what  do we wanna display for know issues? just true/false for intermittent or add the notes field if exists? 
collpased:
collpases

expanded:
expand

**Comment by mwasilew** [comment]
I'd say display all bits of known issues if they exist.

**Comment by mwasilew** [comment]
Let's also be consistent about collapsed/expanded marks. Project listing uses >> and <<.

**Comment by amrohassaan** [comment]
@mwasilew how about now?
Expanded
expanded

Collapsed
collapsed

**Comment by mwasilew** [comment]
This looks nice, let me check it locally.

**Comment by mwasilew** [comment]
Issues I found:
 * Test log is not displayed in the test details page
 * In test details there is always >> next to test result even if the test or suite don't have any steps to reproduce or description
 * clicking on 'full log' in test list page leads to 404 because of incorrect url pattern
 * comparison links don't work. They cause server errors on XHR. Example URL: http://127.0.0.1:8000/api/projects/113/test_results/?limit=10&test_name=cts-lkft-armeabi-v7a%2Farmeabi-v7a.CtsCameraTestCases%2Fandroid.hardware.camera2.cts.AllocationTest.testAllocationFromCameraFlexibleYuv

**Comment by amrohassaan** [comment]
> Issues I found:
> 
> * Test log is not displayed in the test details page
>>I think it could be something on your side @mwasilew . Me and @chaws are getting the same views and we couldn't reproduce this. works as expected for both of us.
> * In test details there is always >> next to test result even if the test or suite don't have any steps to reproduce or description
>> Fixed.
> * clicking on 'full log' in test list page leads to 404 because of incorrect url pattern
>>Same like point above. We couldn't reproduce.
> * comparison links don't work. They cause server errors on XHR. Example URL: http://127.0.0.1:8000/api/projects/113/test_results/?limit=10&test_name=cts-lkft-armeabi-v7a%2Farmeabi-v7a.CtsCameraTestCases%2Fandroid.hardware.camera2.cts.AllocationTest.testAllocationFromCameraFlexibleYuv
>> Same like test log, me and Charles are not getting to see this URL at all. Comparison works fine as expected as well.

**Comment by mwasilew** [comment]
@amrohassaan I shared a video showing the bugs. There are very real and only on your branch. Don't happen on master.

**Comment by mwasilew** [comment]
Ah, managed to get it to youtube :)
https://www.youtube.com/watch?v=p6d6LaMYiTU
Change quality to HD, otherwise it will be blurred.

**Comment by mwasilew** [comment]
Please also check why the lists of tests before and after applying the patch are different. This is a bit worrying. Test list doesn't match the number of failed tests at least.

**Comment by amrohassaan** [comment]
@mwasilew it turns out it is only android-lkft project that gives those errors and it is all due the funky "$" in the suite name. Url should be working now in viewing log or comparing tests. Regarding the the varying numbers of tests in test list. I cannot see a diff in numbers between master and this branch. Can you point me to which proj/build/suite you saw this? meanwhile i will keeping testing maybe i can find it.

**Comment by mwasilew** [comment]
You're right. I selected different suite. This is the reason numbers differ.

**Comment by amrohassaan** [comment]
@mwasilew fixed as per our sync notes.

**Comment by chaws** [comment]
Code looks good! Nice to see less clicking to see test info.

While reviewing the PR, I ran into 2 issues, but that was there before this patch:
* in test_history, after clicking "Permanlink" pagination doesn't get highlighted when you change pages
* there's a lot of duplicated queries loading test history

**Pull request merged**
