### PR TITLE
frontend: build_callbacks: add callbacks to the Build view

### PR DESCRIPTION
**Pull request by chaws**
Fixes https://github.com/Linaro/squad/issues/973

And it'll look like this:

Screenshot from 2021-04-07 17-59-19

### CODE REVIEW

**Comment by jscook2345** [comment]
Looks good to me, with a few notes.

1. I think `jinja` automatically takes care of escaping variables for you. If not, or if you have a setting disabling that, some of the variables may need to be escaped.

2. It looks like their is a travis failure having to due with a locked table.

3. What does this look like with zero callbacks?

4. What does this look like with more than one callback?

Thanks for your work on this!

**Comment by chaws** [comment]
> 1. I think jinja automatically takes care of escaping variables for you. If not, or if you have a setting disabling that, some of the variables may need to be escaped.

It's configured for auto-escape template strings: https://github.com/Linaro/squad/blob/master/squad/jinja2.py#L41. I had that concern when presenting the `Response content`, which should contain JSON only, but who knows! I think it's protected against that. Thanks for pointing it out tho.

> 2. It looks like their is a travis failure having to due with a locked table.

Dunno why that happens, it's not every time. For some reason I can't restart the job, probably because travis is migrating to *.com, I might have to enable github actions for squad. Bottom line is this error is "OK", since it breaks in sqlite while in postgres (production) it's green.

> 3. What does this look like with zero callbacks?

No "Callbacks" tab.

> 4. What does this look like with more than one callback?

See the bullet in front of "POST / ...", there's a loop iterating over all `build.callbakcs` and each callback will be an `<li>`, just like that first one you see.

**Comment by chaws** [comment]
@jscook2345 Just fixed the issue that was breaking travis.

**Comment by jscook2345** [comment]
LGTM! Merge away! 🥇

**Pull request merged**
