### PR TITLE
frontend: fix filtering box in build view

### PR DESCRIPTION
**Pull request by mwasilew**
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>

### CODE REVIEW

**Comment by chaws** [comment]
LGTM

**Comment by mwasilew** [comment]
This patch improves things but it's not complete. We're not filtering in envs/suites table contents. I didn't find a good solution for that yet.

**Comment by chaws** [comment]
I think it already handles that. Because `match` will match the whole tag, if you type the environment name it'll display only tags with that environment filtered.

**Comment by mwasilew** [comment]
My point is that the whole environment table is displayed even if user wants to filter on the test across envs. So I think we'll need to enable that somehow.

**Pull request merged**
