### PR TITLE
ci: lava: update TestJob name and status

### PR DESCRIPTION
**Pull request by mwasilew**
Name of the TestJob is updated either during submission of at the ZMQ
event. TestJob status is updated on ZMQ event. This allows to check the
job progress 'live' in the squad UI.

Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>

### CODE REVIEW

**Comment by mwasilew** [comment]
I didn't test it locally yet. Hopefully this will happen later today :)

**Comment by terceiro** [comment]
hi, is this is stil WIP?

**Comment by mwasilew** [comment]
Yes, I didn't get to test it yet :(

**Comment by mwasilew** [comment]
I tested locally. Once unit tests complete it's ready for review.

**Pull request merged**
