### PR TITLE
Add totals test results build view

### PR DESCRIPTION
**Pull request by chaws**
Close https://github.com/Linaro/squad/issues/781

Here's a snapshot of what's looking like:

Screenshot from 2020-07-31 19-35-30

### CODE REVIEW

**Comment by mwasilew** [comment]
LGTM. Would it be possible to also add summaries to suites x envs view?

**Comment by chaws** [comment]
Hum, I thought about it but didn't know where to place it in the layout. Under suite name?

**Comment by chaws** [comment]
@mwasilew I've added to suites x environments as you asked. It looks OK in some cases but kinda odd in cases were there are multiple statuses per environment.

Regular (most cases):
Screenshot from 2020-08-03 23-09-43


Cases when there are multiple statuses per env. Notice the boot suite:

Screenshot from 2020-08-03 23-10-41

**Comment by mwasilew** [comment]
@chaws yeah, we should group the statuses when there is more than one and provide the 'confidence score'. But that's not yet implemented. @danrue what do you think? Does this look OK for you, or it's too early to introduce? We could go with first set of patches (for suites and envs views only) and leave this bit for later (after confidence score is implemented).

**Comment by chaws** [comment]
@mwasilew I removed the changed in suite x environments layout for now and will be landing an new PR with that soon.

**Pull request merged**
