### PR TITLE
frontend: prioritize display of failures and add filtering

### PR DESCRIPTION
**Pull request by terceiro**
- Test suites with failures are displayed on top
- Test suites without failures are hidden by default and can be toggled
- If there are no test suites with failures, everything is shown

### CODE REVIEW

**Comment by terceiro** [comment]
screnshots:

non-failures are hidden by default:

0_show

and can be displayed:

1_hide

**Comment by terceiro** [comment]
the other features I'm working on build on top of the original commits I included in this PR, so I am appending them here.

**Comment by terceiro** [comment]
build page, no filtering:

0_build_no_filter

build page, filtered:

1_build_filtered

test results page, no filter (not tests with failures on top):

2_test_results_no_filter

test results page, filtered:

3_test_results_filtered

**Comment by danrue** [comment]
This looks like a really nice improvement to me. The only thing that caused me pause is the behavior "If there are no test suites with failures, everything is shown". This seems a bit unexpected/clever and most users may never realize why sometimes they get a list of tests and sometimes they don't, causing a (little) bit of cognitive overhead. I don't feel very strongly either way, but I do suspect it would probably be a little better if it was consistent and either always hid success or always showed success.

**Comment by terceiro** [comment]
ok, good point. after I implemented the filtering, I also thought that the hiding the non-failures by default is a little too much, also because the failures are already on top. maybe we could drop the requirement to hide the non-failures?

**Comment by danrue** [comment]
Showing by default is fine with me. I'm trying to be aware of the time it takes someone to get used to the UI, especially some of the more subtle parts.

**Comment by danrue** [comment]
Sure showing them by default is fine. From my perspective, there's a lot of screen in squad and it can take a while to get used to each of them and the navigation (which can be subtle)

**Comment by mwasilew** [comment]
I think we can drop the 'hide passed' feature once we have pagination. The list of tests/testjobs may become very long. So currently I would rather go with 'show nothing in case of all passed' than change the logic basing on results.

**Comment by terceiro** [comment]
OK, so I reworked the code to always hide non-failures in the build page.

**Comment by mwasilew** [comment]
@terceiro did you push your changes already?

**Comment by terceiro** [comment]
@mwasilew yes!

**Comment by terceiro** [comment]
(I rebased and applied the necessary changes do the existing commits)

**Comment by mwasilew** [comment]
I think it's good to go now.

**Pull request merged**
