### PR TITLE
Build confidence project settings

### PR DESCRIPTION
**Pull request by jscook2345**
These settings help users to determine if a regression is from a test
that performs well or performs poorly (flakey)

Signed-off-by: Justin Cook <justin.cook@linaro.org>

### CODE REVIEW

**Comment by jscook2345** [comment]
127 0 0 1_8000_bob_bob_settings_build_confidence_

**Comment by jscook2345** [comment]
Draft: Wish to discuss with @chaws first

**Comment by jscook2345** [comment]
@chaws Ready for review! Thanks!

**Comment by chaws** [comment]
Thanks for the PR! LGTM

**Pull request merged**
