### PR TITLE
Download static assets from their original locations

### PR DESCRIPTION
**Pull request by terceiro**
This will make it easier to run on non-Debian systems

### CODE REVIEW

**Comment by terceiro** [comment]
ok, now I'm really done with this. we have handling updates, download hash verification and whatnot. Let's see what you guys think

**Comment by danrue** [comment]
:1st_place_medal: I think you just created a new standard. Nice work!

**Comment by mwasilew** [comment]
why didn't we use node.js for this? It would be as easy as 'npm install..'

**Comment by terceiro** [comment]
my goal was exactly to avoid a dependency on nodejs ...

**Pull request merged**
