### PR TITLE
Use storage

### PR DESCRIPTION
**Pull request by chaws**
Inspired from https://github.com/Linaro/squad/pull/850

This PR makes use of storage fields without removing legacy ones. The intention is to start saving data to both DB and S3 so that when migrate legacy data to S3 we'll be sure that no data will be lost.

Next step will be replacing db data by S3 data.

### CODE REVIEW

**Comment by mwasilew** [comment]
+1. Please merger if the tests complete today.

**Comment by chaws** [comment]
Please don't merge it yet!

**Comment by chaws** [comment]
I think the script to move files to storage is not doing it correctly, combining DB offset and filtering might skip processing some testruns, i'll send a fix today

**Comment by chaws** [comment]
I think I got it right this time.

Migration script takes 1000 testruns at a time per thread. Then it iterates over its attachments to also save it to S3.
Running this locally I got up to 400 testruns per second, but it'll depend heavily on `tests_file` and attachments.

Occasionally I ran out of memory, I don't know why Django won't free memory though.

**Comment by mwasilew** [comment]
LGTM. Should I merge it now?

**Comment by chaws** [comment]
@mwasilew yes, please! Once merged, i'll fire start up exporting files in staging

**Pull request merged**
