### PR TITLE
frontend: redesign build page for speed

### PR DESCRIPTION
**Pull request by terceiro**

### CODE REVIEW

**Comment by terceiro** [comment]
screenshots of the new UI:

overview of the test results:

screenshot_2018-08-16 squad -

displaying details for a given suite:

screenshot_2018-08-16 squad - 1

**Comment by terceiro** [comment]
cc @amrohassaan

**Comment by amrohassaan** [comment]
@terceiro , @mwasilew this looks great. +1
Haven't pulled it yet to try its speed and layout but from Antonio's description this is a much better design.

**Comment by mwasilew** [comment]
I like it. If there are no objections by the end f my working day today, I'll merge it.

One small improvement might be allowing for row expansion by clicking on test suite name. But that's minor and we can fix that later.

**Pull request merged**
