### PR TITLE
Lava xml requests transport

### PR DESCRIPTION
**Pull request by mwasilew**
It's a potential fix for issues with pods hanging on pending requests to LAVA.

### CODE REVIEW

**Comment by mwasilew** [comment]
Hmm, it doesn't look OK. Github picked older version of the patch. Please don't merge yet before this issue is resolved.

**Comment by mwasilew** [comment]
I think I pushed to wrong branch. Should be fixed now.

**Comment by chaws** [comment]
LGTM, I think testing timeouts is a bit tricky, but those should be OK

**Comment by mwasilew** [comment]
tests only check what happens if actual timeout happens. I didn't write any tests that trigger the timeout in requests. Let's see if this helps getting rid of the strange suspended pods.

**Comment by chaws** [comment]
I'm keeping an eye one the queue length since then. I'll roll this out to prod today and keep an eye as well. I'm also considering change auto scale metrics from cpu usage to number of tasks in the queue.

**Pull request merged**
