### PR TITLE
highlighted the test run environment and test suite in the page header

### PR DESCRIPTION
**Pull request by situmam**
Currently the test suite and test environment (squad talk for test board) are not easy to distinguish in the test run and test suite pages. This pull request adds them into the page header, adds an icon to easy for easy understanding and highlights the values so they are easy to pick out visually.

### CODE REVIEW

**Comment by mwasilew** [comment]
@situmam could you edit commit messages to have a one-line summary and the rest of the commit below it? Apart from that looks good to me.

**Comment by situmam** [comment]
I did amend my commit with a better oneline message. Please let me know if this is satisfactory.

**Comment by danrue** [comment]
:+1: looks good to me

**Comment by mwasilew** [comment]
I edited the commit messages and rebased on top of current master. The patches are now merged. Closing this PR.

**Pull request closed without merging**
