### PR TITLE
core: rest: add top-level metric endpoint

### PR DESCRIPTION
**Pull request by amrohassaan**
Add top level metric ep similar to tests.

### CODE REVIEW

**Comment by chaws** [comment]
I fetched your branch locally and it worked just fine :)
Only request I make is to add a test for this in `test/api/test_rest.py`

**Comment by amrohassaan** [comment]
Tests in.

**Comment by amrohassaan** [comment]
Closes issue #673

**Comment by chaws** [comment]
Looks good to me!

**Pull request merged**
