### PR TITLE
frontend: prevent displaying 'secrets' from LAVA job definition

### PR DESCRIPTION
**Pull request by mwasilew**
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>

### CODE REVIEW

**Comment by chaws** [comment]
The definitions look way better once yaml is parsed, but I think it'd be useful to let the user know there was a `secrets` block in the definition. Since [documentation](https://validation.linaro.org/static/docs/v2/publishing-artifacts.html?highlight=secrets) says that secrets is a key-value array, I think it's worth  replacing secrets to something like `****`

**Comment by mwasilew** [comment]
I guess this can be done. Not very costly.

**Comment by mwasilew** [comment]
I pushed new version of the patch.

**Comment by chaws** [comment]
LGTM

**Pull request merged**
