### PR TITLE
Bump to Django 3.2

### PR DESCRIPTION
**Pull request by chaws**
Fix https://github.com/Linaro/squad/issues/1015

### CODE REVIEW

**Comment by chaws** [comment]
@terceiro I'm bumping Squad to Django 3.2. Until now it has been going ok. But now it's hitting a cyclic dependency import error that just does't make sense to me.

I updated `Dockerfile` to `FROM bullseye-backports` and changed how some of the python packages get installed (moved from pip to deb). So far so good. The problem starts when Squad get's invoked:

```dockerfile
# Ref https://github.com/Linaro/squad/blob/master/Dockerfile#L74
squad-admin collectstatic --noinput --verbosity 0 && \
```

I get this import error:
```python
Traceback (most recent call last):
  File "/usr/local/bin/squad-admin", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/squad/manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 16, in setup
    from django.urls import set_script_prefix
  File "/usr/lib/python3/dist-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/usr/lib/python3/dist-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
  File "/usr/lib/python3/dist-packages/django/http/__init__.py", line 1, in <module>
    from django.http.cookie import SimpleCookie, parse_cookie
  File "/usr/lib/python3/dist-packages/django/http/cookie.py", line 1, in <module>
    from http import cookies
  File "/usr/local/lib/python3.9/dist-packages/squad/http.py", line 2, in <module>
    from django.http import HttpResponseForbidden, JsonResponse
ImportError: cannot import name 'HttpResponseForbidden' from partially initialized module 'django.http' (most likely due to a circular import) (/usr/lib/python3/dist-packages/django/http/__init__.py)
```

From my understanding, things start to go bananas in `from http import cookies`. I know this package belongs to [Python's stdlib](https://docs.python.org/3.9/library/http.html) 3.7+. But from the stack trace, it seems that Python is using `squad.http` instead!

If I renamed `squad/http.py` to `squad/myhttp.py` the error goes away, but the fear stays.

It seems that Python is prioritizing Squad's path? Have you seen/heard something related to this behavior? I don't know if this is related to Django or Python (most likely?).

Thanks in advance!

**Comment by chaws** [comment]
New finding! I've placed `print(sys.path)` in the first line of `squad/http.py` and got these for:
* master's Dockerfile
`['/usr/local/bin', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/']`
* this PR's Dockerfile
`['/usr/local/lib/python3.9/dist-packages/squad', '/usr/local/bin', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages']`

The occurency of `'/usr/local/lib/python3.9/dist-packages/squad'` in the path tells us why squad's modules are taking precedence when Django imports stuff. But why?

**Comment by terceiro** [comment]
I started looking into this. I tried `./dev-docker` on your PR branch, and there I don't see this issue. So the issue could be pinpointed to the part of the `Dockerfile` that `dev-docker` doesn't use, namely:

```dockerfile
COPY . /squad-build/                                                             
                                                                                 
ENV SQUAD_STATIC_DIR=/app/static                                                 
                                                                                 
RUN cd /squad-build && ./scripts/git-build && \                                  
    pip3 install --no-dependencies ./dist/squad*.whl && \                        
    cd / && rm -rf /squad-build && apt-get remove -y git && apt-get autoremove -y && \
    mkdir -p /app/static && \                                                    
    useradd -d /app squad && \                                                   
    python3 -m squad.frontend && \                                               
    squad-admin collectstatic --noinput --verbosity 0 && \                       
    chown -R squad:squad /app && \                                               
    cd `python3 -c 'import squad; print(squad.__path__[0])'` && squad-admin compilemessages && \
    cd /app                                                                      
                                                                                 
USER squad                                                                       
```

**Comment by terceiro** [comment]
> ```dockerfile
>     cd `python3 -c 'import squad; print(squad.__path__[0])'` && squad-admin compilemessages && \
> ```

the problem is here:

```
# python3 -c 'import squad; print(squad.__path__[0])'
/usr/local/lib/python3.9/dist-packages/squad
```

To be able to compile the translations, one needs to be in the app source directory. But this compilation is also already done in `scripts/git-build`, so this can be skipped. Just drop that line.

**Comment by chaws** [comment]
Whaaaaaat? I can't believe it was jsut that! Thanks a lot @terceiro !

One thing that I still don't understand is how come this was never a problem before the bump to Python 3.9? I still think this must have something related to the way Python 3.9 does imports... but well, I already spent perhaps too much time on it.

Thanks again, @terceiro ! I'll update the PR and push it to staging.

**Pull request merged**
