### PR TITLE
Migrate to django2

### PR DESCRIPTION
**Pull request by chaws**
This is a work in progress patch that migrates our base framework from Django 1.11 LTS to 2.2 LTS. The changes are described below:

Django 1.11 -> 2.2 [1]
- s/from django.core.urlresolvers import reverse/from django.urls import reverse/
- s/MIDDLEWARE_CLASSES/MIDDLEWARE/ (settings.py)
  - MIDDLEWARE has a new format
- s/django.shortcuts.render_to_response()/django.shortcuts.render()/
- s/User.is_authenticated()/User.is_authenticated/
- s/User.is_anonymous()/User.is_anonymous/
- d/SessionAuthenticationMiddleware/ (settings.py)
- s/@register.assignment_tag/@register.simple_tag/
- s/ForeignKey()/ForeignKey(on_delete=models.CASCADE)/
- s/OneToOne()/OneToOne(on_delete=models.CASCADE)/
- d/Manager.use_for_related_fields/ (squad/core/models.py:539)

Python >= 3.3
- mock is now part of Python3 std library [2]
- 'logger.warn' is deprecated in favor of 'logger.warning' [5]
- should we enforce >= 3.6?
  - weakref bug: https://bugs.python.org/issue29519

Django Rest Framework >= 3.9.2 
- 3.9.2 is ensures support to Django 2.2 [3]
- s/detail_route/action(detail=True)/

Django Filters >= 2.0 [4]
- s/Filter.name/Filter.field_name/

Django Rest Framework Filters >= 1.0.0dev0
- current version doesn't support Django 2.2
- we should wait for 1.0 to be released

References:
[1] https://eldarion.com/blog/2017/12/26/10-tips-upgrading-django-20/
[2] https://docs.python.org/3/library/unittest.mock.html
[3] https://www.django-rest-framework.org/community/release-notes/#392
[4] https://django-filter.readthedocs.io/en/master/guide/migration.html
[5] https://docs.python.org/3/library/logging.html#logging.Logger.warning

### CODE REVIEW

**Comment by terceiro** [comment]
FWIW, I tested this on Debian unstable, and after updating a couple of
packages¹² I got it to work just fine, both passing all tests and running the
UI successfully on my machine.

¹ [djangorestframework-filters](https://tracker.debian.org/news/1054466/accepted-djangorestframework-filters-100dev0-1-source-into-unstable/)
² [python-django-extensions](ttps://tracker.debian.org/news/1054468/accepted-python-django-extensions-221-1-source-into-unstable/)

The diff seems reasonable, so overall this looks good to me.

**Comment by chaws** [comment]
Thanks for testing it! 

> ...after updating a couple of packages...

Cool! Did you have any issues with `django_extensions`?

Also, I saw that in Debian buster the default Python3 is 3.7, so I guess it's safe to state that squad is compatible with Python3. I mean that because of the [weakref](https://github.com/Linaro/squad/issues/554#issuecomment-515172222) bug.

**Comment by terceiro** [comment]
> Cool! Did you have any issues with `django_extensions`?

I often use runserver_plus and shell_plus, and at least runserver_plus didn't work. I didn't note the actual error, but upgrading to the newest upstream version made it work.

**Comment by chaws** [comment]
@terceiro , I've updated travis' build environment to "xenial". The previous one, "trusty", had an old version of Sqlite3 (5 years old!) and it was causing tests to crash because Django 2.2 required a more recent version of it, whereas Django 2.1 didn't. Nevertheless, I opted to update travis' to a more recent distro rather than downgrading Django.

Also, I managed to overcome incompatibilities between "django_restframework_filters" by adding `compat.py`. It seems it's a common place to add compatibility code in packages. Please correct me if you think it's weird.

**Comment by terceiro** [comment]
migrated to  #585

**Pull request closed without merging**
