### PR TITLE
core: add PluginScratch object

### PR DESCRIPTION
**Pull request by mwasilew**
The intention is to save big pieces of string used by plugin tasks into
database. This will prevent crashing message queue brokers due to OOM
conditions.

Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>

### CODE REVIEW

**Comment by chaws** [comment]
LGTM, I also think it's a good idea to write a cron job to remove "old" plugin data, let's say a month old?

**Comment by mwasilew** [comment]
These objects should be removed by plugin after they use the data. This way I will be able to tell when the plugin postprocessing is done and notifications can be sent. So there should be no permanent scratch objects in the database.

**Comment by chaws** [comment]
Makes sense, I thought of it because I was afraid there would be no way to run a function when a task in celery chord fail, but apparently that's easy to handle https://stackoverflow.com/questions/29355613/run-a-chord-callback-even-if-the-main-tasks-fail

**Comment by mwasilew** [comment]
I'll figure something out. IMHO the sequence should be as follows:
 - task clears after itself (deletes scratch object)
 - in case of crash, scratch is removed when handling exception
 - in case of OOM, there is an error callback in chord
I hope this is good enough to prevent residual scratch objects.

**Pull request merged**
