### PR TITLE
frontend: improve project listing

### PR DESCRIPTION
**Pull request by terceiro**

### CODE REVIEW

**Comment by terceiro** [comment]
normal screen(1024px wide):

project-list

small screen:

project-list-smallscreen

**Comment by danrue** [comment]
What does the little graph icon with numbers next to it mean? "2.045"?

**Comment by terceiro** [comment]
On Wed, Sep 20, 2017 at 07:36:55PM +0000, Dan Rue wrote:
> What does the little graph icon with numbers next to it mean? "2.045"?

It's the icon I found for "metrics". that number if the "metrics
summary", which is the geometric mean of all metric values. This is a
concept inherited from ART reports.

**Comment by mwasilew** [comment]
I like it :)

**Comment by mwasilew** [comment]
Looks ok. I just have one hesitation - shouldn't we hide the descriptions by default? They can be lengthy and make the page look messy.

**Comment by terceiro** [comment]
we can display the first N characters of the description, and have a button to expand it. I think that's better than hiding by default and letting the user figure out how to display it

**Comment by mwasilew** [comment]
This might be hard on html tags, but I'm OK with it.

**Comment by terceiro** [comment]
OK, limited the size of the descriptions, and added a "Show more"/"Show less" button.  Also added a very light gray background to each project so that the division between them becomes even more clear. Updated screenshots below.

1024 px wide:

project-list

360px wide:

project-list-smallscreen

**Pull request merged**
