### PR TITLE
core: add management command to create/update auth tokens

### PR DESCRIPTION
**Pull request by mwasilew**
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>

### CODE REVIEW

**Comment by mwasilew** [comment]
This was requested for creating/updating tokens when working in docker-compose environments with LAVA.

**Comment by terceiro** [comment]
can we add a "set-token" action to the existing `users` command instead?

**Comment by terceiro** [comment]
or a --token option to the existing add and update actions there

**Comment by mwasilew** [comment]
I think 1st option is better/easier

**Comment by chaws** [comment]
LGTM

**Pull request merged**
